# Generated by Django 5.0.3 on 2024-03-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='user_id',
            field=models.CharField(default='NoAuth', max_length=200),
            preserve_default=False,
        ),
    ]
